### ISSUE TITLE
Als Nutzer*in möchte ich nach dem erfolgreichen Einloggen eine Übersicht über meine bereits ausgeführten und laufenden Jobs, sowie die Option eine Demo aufzurufen erhalten

### ISSUE THREAD

**Issue by nschnierer** [digital-peaks/web-aoa#26]
### Komplette Story
Als Nutzer*in möchte ich nach dem erfolgreichen Einloggen auf eine Oberfläche weitergeleitet werden, auf der ich eine Übersicht über bereits ausgeführte und laufende Jobs habe sowie die Option einen Beispieldatensatz zu Demozwecken aufzurufen. Auch die Prozessierungsreports dieser Jobs stehen mir hier zur Verfügung. 

### Beschreibung
<img width="500" alt="Bildschirmfoto 2021-12-08 um 13 06 35" src="https://user-images.githubusercontent.com/3831579/145205776-1ab0f79e-7ccc-4e3e-a2dc-903a5ff5ca29.png">

### Akzeptanzkriterien
* Nach einem erfolgreichen Login wird man auf die Job Übersichtsseite weitergeleitet
* Auf dieser Seite habe ich die Möglichkeit eine Demo zu starten
  * Der Button "Start demo" wird links neben "Create new job" platziert
* Laufende und abgeschlossene Jobs (dies kann eine Demo oder ein erstellter Job sein) werden in der Liste dargestellt
  * Die neuesten Einträge werden immer oben angezeigt
* Zu jedem Job kann ich den aktuellen Status einsehen (laufend, Fehler, Fertig)
* Der Prozessierungsreport ist über den Job erreichbar, indem man diesen anklickt (in der Job-Ansicht kann der Report eingesehen werden)

### Tasks

- [x] #65
- [x] digital-peaks/web-aoa-frontend#59
- [x] #67
- [x] digital-peaks/web-aoa-frontend#117
- [x] digital-peaks/web-aoa-frontend#95
