### ISSUE TITLE
Als Nutzer*in möchte ich die Möglichkeit haben, über einen Button oder die Navigationsleiste auf eine Seite weitergeleitet zu werden, auf der ich neue Parameter eingeben kann, um einen neuen Job zu erstellen.

### ISSUE THREAD

**Issue by nschnierer** [digital-peaks/web-aoa#27]
### Beschreibung
<img width="500" alt="Bildschirmfoto 2021-12-08 um 13 10 59" src="https://user-images.githubusercontent.com/3831579/145206280-49469c4b-de00-4321-8162-c9bdd6296088.png">

> Soll auch auf mobilen Endgeräten funktionerien.

### Tasks

- [x] #16 
- [x] #13 
- [x] #6 
- [x] #4 
- [x] #3 
- [x] #46 
- [x] digital-peaks/web-aoa-frontend#2
- [x] digital-peaks/web-aoa-frontend#3
- [x] digital-peaks/web-aoa-frontend#5
- [x] digital-peaks/web-aoa-frontend#31
- [x] digital-peaks/web-aoa-frontend#47
- [x] digital-peaks/web-aoa-frontend#92
- [x] digital-peaks/web-aoa-frontend#91
- [x] digital-peaks/web-aoa-frontend#90
- [x] digital-peaks/web-aoa-frontend#83
- [x] digital-peaks/web-aoa-frontend#74
