### ISSUE TITLE
Als Biolog*in möchte ich die Möglichkeit haben, das trainierte Modell, welches ich mit von mir erhobenen räumlichen Daten über von Wasserflächen im bewaldeten Untergrund trainiert habe, auf seine Nutzbarkeit in einem Gebiet Mitteldeutschlands zu testen. Dabei habe ich den Random-Forest-Machine-Learning-Algorithmus verwendet.

### ISSUE THREAD

**Issue by nschnierer** [digital-peaks/web-aoa#29]
### Tasks
- [x] Testdaten hochladen, welche zum Beispiel Wasserflächen enthalten und dabei den Random-Forest-Machine-Learning-Algorithmus verwenden.
- [x] Das Modell downloaden 
- [x] Das Modell hochladen und auf ein anderes Gebiet zum Testen anwenden (zum Beispiel im Gebiet Mitteldeutschland)

**Comment by Timo123456789** [comment]
@xcomagent95 Ist diese Story vielleicht besser mit einem weiteren Indize zu lösen? NDVI oder so? Du wolltest da ja noch möglicherweise etwas einbauen.
War das richtig das die Klassifikation bei Wasserflächen nicht vernünftig funktioniert?

**Comment by xcomagent95** [comment]
Der NDVI ist bereits eingebaut und kann in Modellen verwendet werden. Bei Wasserflächen sollte es dem Modell recht leicht fallen dieses zu erkennen da Wasser in recht vielen spektralen Bereichen eindeutig zu erkennen ist ;)
