### ISSUE TITLE
Als Geoinformatiker*in möchte ich die Möglichkeit haben, das trainierte Modell, welches ich mit dem Vorkommen von Photovoltaik Anlagen auf Dächern in Münster trainiert habe, auf seine Nutzbarkeit in Südafrika zu testen. 

### ISSUE THREAD

**Issue by nschnierer** [digital-peaks/web-aoa#30]
### Tasks
- [x] Testdaten hochladen, welche zum Beispiel Photovoltaik Anlagen enthalten 
- [x] Das Modell downloaden 
- [x] Das Modell hochladen und auf ein anderes Gebiet zum Testen anwenden (zum Beispiel in Südafrika)

**Comment by JudithBre** [comment]
@nschnierer müssen die User-Stories alle genau so umgesetzt werden oder können wir diese User-Story abwandeln? Gerade die User-Story mit den Photovolataik Anlagen ist doch recht aufwändig und damit zeitintensiv.
