### ISSUE TITLE
Als Nutzer*in habe ich die Optionen ein trainiertes Modell oder Trainingsdaten hochzuladen.

### ISSUE THREAD

**Issue by nschnierer** [digital-peaks/web-aoa#31]
### Komplette Story
Als Nutzer*in habe ich die Option ein trainiertes Modell hochzuladen, um die Klassifizierung durchzuführen und die AOA zu berechnen.
Alternativ können Trainingsdaten (GeoJSON, GeoPackage) hochgeladen werden, um das Training und die Klassifizierung durchzuführen sowie die AOA zu berechnen.

### Akzeptanzkriterien
 * Es muss möglich sein ein Modell im Format *.rds hochzuladen
 * Es muss möglich sein die Trainingsdaten als GeoJSON oder GeoPackage hochzuladen
 * Die jeweiligen Dateien können über eine Schaltfläche ausgewählt werden
 * Eine Datei darf nicht größer als 10 MB sein (aktuelles Limit, soll aber flexibel anpassbar sein, ohne den Code zu verändern)

### Tasks
- [x] Es ist möglich ein Modell im Format *.rds hochzuladen
- [x] Es ist möglich die Trainingsdaten als GeoJSON oder GeoPackage hochzuladen
- [x] Die jeweiligen Dateien können über eine Schaltfläche ausgewählt werden
- [x] Die Dateigröße ist auf 10 MB beschränkt

**Comment by nschnierer** [comment]
Ein Modell und die Trainingsdaten gleichzeitig zu nutzen ergibt aus aktuellen Erkenntnissen wenig Sinn.
Ggf. ist hier ein Change-Request erforderlich.

**Comment by JudithBre** [comment]
Ich beantrage eine Umbennenung der User Story in  
**Als Nutzer*in habe ich die Optionen ein trainiertes Modell  oder Trainingsdaten hochzuladen #31** 

Ein **Change Request** wurde von  [Edzer Pebesma](https://github.com/edzer/) und [Christian Knoth](https://github.com/DaChro) **akzeptiert**.
siehe auch #69 und #93.

@nschnierer, @Timo123456789, @xcomagent95, @jbalzer12

**Comment by JudithBre** [comment]
Die Änderung/Umbenennung der User Story wird vom gesamten Scrum-Team mitgetragen.
Abgesprochen im heutigen Weekly Scrum am 20.01.2022.
