### ISSUE TITLE
Als Nutzer*in möchte ich mein Untersuchungsgebiet (Area of Interest) auf einer Karte festlegen können, um das Gebiet zu kennzeichnen, für welches die Eignung meines trainierten Modells berechnet werden soll.

### ISSUE THREAD

**Issue by nschnierer** [digital-peaks/web-aoa#32]
### Tasks

- [x] digital-peaks/web-aoa-frontend#13
- [x] digital-peaks/web-aoa-frontend#9
- [x] digital-peaks/web-aoa-frontend#10
