### ISSUE TITLE
Als Nutzer*in möchte ich die Resultate (die Vorhersage, die AOA, die empfohlenen Orte zum Sammeln weiterer Trainingsdaten und ggf. das trainierte Modell) der Prozessierung herunterladen können, um diese in weiteren Verarbeitungsschritten zu nutzen.

### ISSUE THREAD

**Issue by nschnierer** [digital-peaks/web-aoa#41]
### Beschreibung

<img width="500" alt="Bildschirmfoto 2021-12-08 um 13 26 22" src="https://user-images.githubusercontent.com/3831579/145215400-e09cb6ce-8181-418f-be86-4ff9da8b9b8a.png">

### Akzeptanzkriterien
* Der Download-Button wird neben der Beschriftung (ausgeschrieben "Area of Applicablity (AOA)") vom jeweiligen Resulat dargestellt
* Durch das Klicken auf den Button kann der Benutzer die Datei auf seinem Computer speichern
* Die Datei wird eindeutig beschriftet, damit diese zum jeweiligen Resultat zugeordnet werden kann

### Tasks

- [x] digital-peaks/web-aoa-frontend#15
- [x] #55
- [x] #70
- [x] digital-peaks/web-aoa-frontend#85
- [x] digital-peaks/web-aoa-frontend#79
- [x] digital-peaks/web-aoa-frontend#70
