### ISSUE TITLE
Als Nutzer*in möchte ich einige der Resultate der Prozessierung (das Untersuchungsgebiet, die Vorhersage, die AOA, ggf. die Trainingsgebiete, die empfohlenen Orte zum Sammeln weiterer Trainingsdaten und ggf. das trainierte Modell) in einem Web-Interface betrachten können, um sich schnell einen Überblick über das Ergebnis zu verschaffen.

### ISSUE THREAD

**Issue by nschnierer** [digital-peaks/web-aoa#42]
### Tasks

- [x] digital-peaks/web-aoa-frontend#12
- [x] digital-peaks/web-aoa-frontend#11
- [x] digital-peaks/web-aoa-frontend#18
- [x] digital-peaks/web-aoa-frontend#56
- [x] digital-peaks/web-aoa-frontend#57
- [x] digital-peaks/web-aoa-frontend#54
- [x] digital-peaks/web-aoa-frontend#41
- [x] #100
